# Generated by Django 3.1 on 2021-05-02 06:41

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.FileField(default='avtar.jpg', upload_to='image/doctors/')),
                ('FullName', models.CharField(blank=True, max_length=50)),
                ('DOB', models.DateField(default=datetime.datetime(2021, 5, 2, 12, 11, 58, 574832))),
                ('Mobile', models.CharField(blank=True, max_length=10)),
                ('Gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=50)),
                ('About', models.TextField(blank=True, max_length=5000)),
                ('Address', models.TextField(blank=True, max_length=100)),
                ('Country', models.CharField(blank=True, max_length=20)),
                ('State', models.CharField(blank=True, max_length=20)),
                ('City', models.CharField(blank=True, max_length=20)),
                ('Pincode', models.CharField(blank=True, max_length=6)),
            ],
            options={
                'db_table': 'Doctor',
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=50, unique=True)),
                ('Password', models.CharField(max_length=50)),
                ('IsActive', models.BooleanField(default=False)),
                ('DateCreated', models.DateTimeField(auto_now_add=True)),
                ('DateUpdated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Master',
            },
        ),
        migrations.CreateModel(
            name='PetCareTaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.FileField(default='avtar.jpg', upload_to='image/pet-takers/')),
                ('FullName', models.CharField(default='', max_length=50)),
                ('Mobile', models.CharField(default='', max_length=10)),
                ('Gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=50)),
                ('Address', models.TextField(default='', max_length=50)),
                ('Country', models.CharField(default='', max_length=20)),
                ('State', models.CharField(default='', max_length=20)),
                ('City', models.CharField(default='', max_length=20)),
                ('Pincode', models.CharField(default='', max_length=6)),
                ('Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PCHApp.master')),
            ],
            options={
                'db_table': 'PetCareTaker',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Role',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.FileField(default='avtar.jpg', upload_to='image/users/')),
                ('FullName', models.CharField(default='', max_length=50)),
                ('Mobile', models.CharField(default='', max_length=10)),
                ('Gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=50)),
                ('Address', models.TextField(default='', max_length=50)),
                ('Country', models.CharField(default='', max_length=20)),
                ('State', models.CharField(default='', max_length=20)),
                ('City', models.CharField(default='', max_length=20)),
                ('Pincode', models.CharField(default='', max_length=6)),
                ('Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PCHApp.master')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tag', models.CharField(choices=[('skin', 'Skin'), ('ortho', 'Orthopadic')], max_length=50)),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PCHApp.doctor')),
            ],
            options={
                'db_table': 'Specialization',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, unique=True)),
                ('Image', models.FileField(default='service.jpg', upload_to='image/services/')),
                ('Description', models.TextField(max_length=20000)),
                ('IsActive', models.BooleanField(default=False)),
                ('PetCareTaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PCHApp.petcaretaker')),
            ],
            options={
                'db_table': 'Service',
            },
        ),
        migrations.CreateModel(
            name='PetDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('dog', 'Dog'), ('fish', 'Fish'), ('rabbit', 'Rabbit'), ('turtle', 'Turtle')], max_length=50)),
                ('Breed', models.CharField(default='', max_length=50)),
                ('Name', models.CharField(default='', max_length=50)),
                ('Age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('YearMonth', models.CharField(choices=[('mon', 'Month'), ('yr', 'Year')], max_length=50)),
                ('Gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=50)),
                ('Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PCHApp.master')),
            ],
            options={
                'db_table': 'PetDetail',
            },
        ),
        migrations.AddField(
            model_name='master',
            name='Role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PCHApp.role'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Review', models.CharField(max_length=2000)),
                ('Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PCHApp.master')),
                ('PetCareTaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PCHApp.petcaretaker')),
            ],
            options={
                'db_table': 'Feedback',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HospitalName', models.CharField(max_length=20)),
                ('Designation', models.CharField(max_length=50)),
                ('DateFrom', models.DateField()),
                ('DateTo', models.DateField()),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PCHApp.doctor')),
            ],
            options={
                'db_table': 'Experience',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Degree', models.CharField(max_length=50)),
                ('College', models.CharField(max_length=50)),
                ('EndYear', models.CharField(max_length=4)),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PCHApp.doctor')),
            ],
            options={
                'db_table': 'Education',
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='Master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PCHApp.master'),
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Address', models.TextField(max_length=300)),
                ('Image', models.FileField(default='avtar.jpg', upload_to='image/clinics/')),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PCHApp.doctor')),
            ],
            options={
                'db_table': 'Clinic',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now=True)),
                ('Status', models.CharField(default='pending', max_length=50)),
                ('Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PCHApp.master')),
                ('PetCareTaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PCHApp.petcaretaker')),
                ('PetDetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PCHApp.petdetail')),
                ('Service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PCHApp.service')),
            ],
            options={
                'db_table': 'Booking',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.DateTimeField(auto_now=True)),
                ('Symptoms', models.CharField(choices=[('Abdomen - Painful', 'Abdomen - Painful'), ('Abdomen - Swollen', 'Abdomen - Swollen'), ('Anorexia', 'Anorexia'), ('Bad Breath', 'Bad Breath'), ('Bleeding - Wounds', 'Bleeding - Wounds'), ('Bleeding From Ear', 'Bleeding From Ear'), ('Bleeding From Nose', 'Bleeding From Nose'), ('Bleeding From Paw', 'Bleeding From Paw'), ('Blindness', 'Blindness'), ('Blood in Stool', 'Blood in Stool'), ('Blood in Urine', 'Blood in Urine'), ('Breathing - Abnormal', 'Breathing - Abnormal'), ('Chewing or Licking at Skin', 'Chewing or Licking at Skin'), ('Choking', 'Choking'), ('Circling', 'Circling'), ('Constipation', 'Constipation'), ('Coughing', 'Coughing'), ('Dandruff', 'Dandruff'), ('Deafness', 'Deafness'), ('Defecation - Painful', 'Defecation - Painful'), ('Defecation - Straining', 'Defecation - Straining'), ('Defecation - Too Much', 'Defecation - Too Much'), ('Dehydration', 'Dehydration'), ('Diarrhea', 'Diarrhea'), ('Dizziness', 'Dizziness'), ('Dragging Bottom', 'Dragging Bottom'), ('Drooling', 'Drooling'), ('Ears - Discharge', 'Ears - Discharge'), ('Ears - Foul Odor', 'Ears - Foul Odor'), ('Ears - Head Shaking', 'Ears - Head Shaking'), ('Ears - Rubbing', 'Ears - Rubbing'), ('Ears - Swollen', 'Ears - Swollen'), ('Eating - Grass', 'Eating - Grass'), ('Eating - Refusal to Eat', 'Eating - Refusal to Eat'), ('Eating - Regurgitation', 'Eating - Regurgitation'), ('Eating - Weight Gain', 'Eating - Weight Gain'), ('Eating Stool', 'Eating Stool'), ('Eyes - Bulging', 'Eyes - Bulging'), ('Eyes - Cloudy', 'Eyes - Cloudy'), ('Eyes - Discharge', 'Eyes - Discharge'), ('Eyes - Pupils Different Sizes', 'Eyes - Pupils Different Sizes'), ('Eyes - Red', 'Eyes - Red'), ('Eyes - Squinting', 'Eyes - Squinting'), ('Eyes - Tear Staining', 'Eyes - Tear Staining'), ('Eyes - Third Eyelid', 'Eyes - Third Eyelid'), ('Face - Swollen', 'Face - Swollen'), ('Falling Down', 'Falling Down'), ('Fever', 'Fever'), ('Gagging', 'Gagging'), ('Gas', 'Gas'), ('Hair Loss', 'Hair Loss'), ('Head Tilt', 'Head Tilt'), ('Heart Rate - Abnormal', 'Heart Rate - Abnormal'), ('Heat', 'Heat'), ('Hot Spot', 'Hot Spot'), ('Incontinence - Urinary', 'Incontinence - Urinary'), ('Itching and Scratching', 'Itching and Scratching'), ('  Leg - Swollen', '  Leg - Swollen'), ('Lethargy', 'Lethargy'), ('Licking or Chewing at Skin', 'Licking or Chewing at Skin'), ('Limping and Lameness', 'Limping and Lameness'), ('Losing Balance', 'Losing Balance'), ('Lumps', 'Lumps'), ('Bumps and Growths', 'Bumps and Growths'), ('Mouth - Bad Breath', 'Mouth - Bad Breath'), ('Mouth - Foreign Object', 'Mouth - Foreign Object'), ('Mouth - Painful swallowing', 'Mouth - Painful swallowing'), ('Mouth - Smacking Lips', 'Mouth - Smacking Lips'), ('Mouth - Sore', 'Mouth - Sore'), ('Mouth Breathing', 'Mouth Breathing'), ('Nose - Bleeding', 'Nose - Bleeding'), ('Nose - Discharge', 'Nose - Discharge'), (' Panting', ' Panting'), ('Paws - Bleeding', 'Paws - Bleeding'), ('Poisoning', 'Poisoning'), ('Pregnancy', 'Pregnancy'), (' Regurgitation', ' Regurgitation'), ('Reverse Sneezing', 'Reverse Sneezing'), ('Runny Nose', 'Runny Nose'), ('Scooting', 'Scooting'), ('Scratching and Itching', 'Scratching and Itching'), ('Seizures', 'Seizures'), ('Shedding', 'Shedding'), ('Shivering', 'Shivering'), ('Skin - Licking and Chewing', 'Skin - Licking and Chewing'), ('Skin - Lumps', 'Skin - Lumps'), ('bumps and growths', 'bumps and growths'), ('Sneezing', 'Sneezing'), ('Staggering', 'Staggering'), ('Stool - Bloody', 'Stool - Bloody'), ('Stool - Eating', 'Stool - Eating'), ('Stool - Loose', 'Stool - Loose'), ('Stool - Painful', 'Stool - Painful'), ('Tail - Limp', 'Tail - Limp'), ('Thirst - Excessive', 'Thirst - Excessive'), ('Trembling', 'Trembling'), ('Urinary Incontinence', 'Urinary Incontinence'), ('Urination - Frequent', 'Urination - Frequent'), ('Urination - Painful', 'Urination - Painful'), ('Urination - Straining', 'Urination - Straining'), ('Vomiting', 'Vomiting'), ('Watery Eye', 'Watery Eye'), ('Weight Gain', 'Weight Gain')], max_length=70)),
                ('Status', models.CharField(default='pending', max_length=50)),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PCHApp.doctor')),
                ('PetDetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PCHApp.petdetail')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PCHApp.user')),
            ],
            options={
                'db_table': 'Appointment',
            },
        ),
    ]
