# Generated by Django 3.1 on 2021-05-02 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCHApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='DOB',
            field=models.DateField(default=datetime.datetime(2021, 5, 2, 13, 8, 51, 174011)),
        ),
        migrations.AlterField(
            model_name='service',
            name='Name',
            field=models.CharField(choices=[('grm', 'grooming'), ('trn', 'trainning'), ('dc', 'day camp'), ('brd', 'pet boarding')], max_length=70, unique=True),
        ),
    ]
